// ghost {"id":"community.emoji","name":"Emoji","version":"1.1.0","author":"Ghost Typist","description":"Type :) or :crying, then Tab. These are the emojis people send most. Hands use the skin tone in Options.","tags":["abbreviations"],"capabilities":["abbreviations"]}
//
// Type an emoticon or a :word, then Tab. The rows are the ones people actually send:
// Unicode's frequency list, and the faces social media uses more than that list shows.

const rows = [
  { trigger: ":)", text: "😊" },
  { trigger: ":-)", text: "😊" },
  { trigger: ":D", text: "😃" },
  { trigger: ";)", text: "😉" },
  { trigger: ":(", text: "😢" },
  { trigger: ":'(", text: "😭" },
  { trigger: ":')", text: "😂" },
  { trigger: ":P", text: "😛" },
  { trigger: ":p", text: "😛" },
  { trigger: "xD", text: "😆" },
  { trigger: "XD", text: "😆" },
  { trigger: "<3", text: "❤️" },
  { trigger: "</3", text: "💔" },
  { trigger: "B)", text: "😎" },
  { trigger: ">:(", text: "😠" },
  { trigger: "+1", text: "👍{skin}" },
  { trigger: "-1", text: "👎{skin}" },
  { trigger: "(y)", text: "👍{skin}" },
  { trigger: "(n)", text: "👎{skin}" },
  { trigger: ":100", text: "💯" },
  { trigger: ":angel", text: "😇" },
  { trigger: ":angry", text: "😠" },
  { trigger: ":blackheart", text: "🖤" },
  { trigger: ":blossom", text: "🌸" },
  { trigger: ":blueheart", text: "💙" },
  { trigger: ":blush", text: "☺️" },
  { trigger: ":broken", text: "💔" },
  { trigger: ":clap", text: "👏{skin}" },
  { trigger: ":cool", text: "😎" },
  { trigger: ":cry", text: "😢" },
  { trigger: ":crying", text: "😭" },
  { trigger: ":down", text: "👇{skin}" },
  { trigger: ":eyeroll", text: "🙄" },
  { trigger: ":eyes", text: "👀" },
  { trigger: ":facepalm", text: "🤦{skin}" },
  { trigger: ":fire", text: "🔥" },
  { trigger: ":giggle", text: "🤭" },
  { trigger: ":greenheart", text: "💚" },
  { trigger: ":grin", text: "😁" },
  { trigger: ":grinning", text: "😀" },
  { trigger: ":happy", text: "😊" },
  { trigger: ":heart", text: "❤️" },
  { trigger: ":heartbeat", text: "💓" },
  { trigger: ":hearteyes", text: "😍" },
  { trigger: ":hide", text: "🙈" },
  { trigger: ":hug", text: "🤗" },
  { trigger: ":joy", text: "😂" },
  { trigger: ":kiss", text: "😘" },
  { trigger: ":laugh", text: "😆" },
  { trigger: ":lol", text: "😂" },
  { trigger: ":love", text: "🥰" },
  { trigger: ":mad", text: "😡" },
  { trigger: ":muscle", text: "💪{skin}" },
  { trigger: ":music", text: "🎶" },
  { trigger: ":no", text: "👎{skin}" },
  { trigger: ":ok", text: "👌{skin}" },
  { trigger: ":party", text: "🎉" },
  { trigger: ":peace", text: "✌{skin}️" },
  { trigger: ":pensive", text: "😔" },
  { trigger: ":pinkheart", text: "💗" },
  { trigger: ":pleading", text: "🥺" },
  { trigger: ":pray", text: "🙏{skin}" },
  { trigger: ":purpleheart", text: "💜" },
  { trigger: ":raised", text: "🙌{skin}" },
  { trigger: ":relieved", text: "😌" },
  { trigger: ":rofl", text: "🤣" },
  { trigger: ":rose", text: "🌹" },
  { trigger: ":sad", text: "😢" },
  { trigger: ":scream", text: "😱" },
  { trigger: ":shrug", text: "🤷{skin}" },
  { trigger: ":skull", text: "💀" },
  { trigger: ":smile", text: "😄" },
  { trigger: ":smiley", text: "😃" },
  { trigger: ":smirk", text: "😏" },
  { trigger: ":sob", text: "😭" },
  { trigger: ":sparkles", text: "✨" },
  { trigger: ":sparkling", text: "💖" },
  { trigger: ":starstruck", text: "🤩" },
  { trigger: ":sweat", text: "😅" },
  { trigger: ":thanks", text: "🙏{skin}" },
  { trigger: ":thinking", text: "🤔" },
  { trigger: ":thumbsup", text: "👍{skin}" },
  { trigger: ":twohearts", text: "💕" },
  { trigger: ":unamused", text: "😒" },
  { trigger: ":wave", text: "👋{skin}" },
  { trigger: ":wink", text: "😉" },
  { trigger: ":yellowheart", text: "💛" },
  { trigger: ":yes", text: "👍{skin}" },
  { trigger: ":yum", text: "😋" }
];

ghost.define({
  id: "community.emoji",
  name: "Emoji",
  version: "1.1.0",
  author: "Ghost Typist",
  description: "Type :) or :crying, then Tab. These are the emojis people send most. Hands use the skin tone in Options.",
  settings: [
    { id: "skin", title: "Skin tone", type: "choice", value: "👍",
      options: ["👍", "👍🏻", "👍🏼", "👍🏽", "👍🏾", "👍🏿"],
      help: "Hands and people use this tone. Faces such as :) do not." },
    { id: "emoji", title: "Replacements", type: "list",
      columns: [
        { id: "trigger", title: "You type" },
        { id: "text", title: "Emoji" }
      ],
      value: rows,
      help: "Type one, then Tab. :crying is a word and :) is a face. {skin} uses the tone above." }
  ],
  expansionsFrom: "emoji",
  typedExpansions: true
})
